// Generated by gmmproc 2.66.2 -- DO NOT MODIFY!


#include <glibmmconfig.h>
#ifndef GLIBMM_DISABLE_DEPRECATED


#include <glibmm.h>

#include <glibmm/balancedtree.h>
#include <glibmm/private/balancedtree_p.h>


#include <glibmm/balancedtree.h>

namespace
{
} // anonymous namespace


namespace Glib
{


} // namespace Glib

#endif // GLIBMM_DISABLE_DEPRECATED


